---
title: "Calendar for 500: Spring 2024"
date-modified: last-modified
---

This Calendar serves as the final word on all deadlines, deliverables and class sessions. 

## Readings

During the course, we will read Paul Rosenbaum's book **Causal Inference** (abbreviated **PRR CI** in what follows), which is available as an e-book or in paperback for under $15. Please obtain the book before our first class on 2024-01-18, and, if you can, read Chapters 1-3 as soon as possible. 

## Timing and Location

- All classes are held in Wolstein Research Building, Room 1217.
- Zoom recordings will be made available when possible.
- Classes 01, and 12-15 will begin at 8:30 AM and continue until 11:00 AM.
- Classes 02-11 will begin at 9:00 AM and continue until 11:00 AM.

## Email

Contact us at **500-help** at **case** dot **edu** if you have any questions, once the class begins.

## Office Hours

- Our teaching assistant, Leila Hojat, will hold office hours via Zoom on Mondays and Wednesdays from 5 to 6 PM, starting on 2024-01-22 and continuing through 2024-05-01. 
    - TA office hours are **cancelled** on 2024-03-11, 2024-03-13, 2024-04-01, 2024-04-03, 2024-04-08 (due to the eclipse) and 2024-04-17.
    - Zoom details for Leila's office hours are posted to our **Shared Google Drive** and as an announcement on [Canvas](https://canvas.case.edu/).
- Dr. Love will hold office hours after class on Thursdays (11 AM to Noon). Just let him know during class if you want to speak with him afterwards.
- For more information about us, visit [Contact Us](contact.qmd).

## February 2024

LINK | Date | Description
---------: | :-------: | :-----------------------------------------------------
[Lab 1](lab1.qmd) | 02-01 | [Lab 1](lab1.qmd) due to [Canvas](https://canvas.case.edu/) by the start of class
[Class 03](https://github.com/THOMASELOVE/500-classes-2024/tree/main/class03) | 02-01 | **9 - 11 AM** Propensity Scores: Direct Adjustment and 1:1 Matching <br /> Discussion of [Lab 1](lab1.qmd) Sketch <br /> Readings: (1) **PRR CI** through Chapter 4, <br /> From [Sources](https://github.com/THOMASELOVE/500-sources): (2) Connors 1996, <br /> From [Sources](https://github.com/THOMASELOVE/500-sources): (3) Gum 2001
[OSIA](osia.qmd) | 02-06 | **Tuesday** 9 AM: [OSIA selections due](osia.qmd) via email to **500-help**
[Class 04](https://github.com/THOMASELOVE/500-classes-2024/tree/main/class04) | 02-08 | **9 - 11 AM** Propensity Scores: More on Matching with the Propensity Score <br /> Readings from [Sources](https://github.com/THOMASELOVE/500-sources): (1) Austin and Mamdani 2006, <br /> From [Sources](https://github.com/THOMASELOVE/500-sources): (2) Normand 2001, <br /> From [Sources](https://github.com/THOMASELOVE/500-sources): (3) D'Agostino Jr 1998
[Lab 2](lab2.qmd) | 02-15 | [Lab 2](lab2.qmd) due to [Canvas](https://canvas.case.edu/) by the start of class
[Class 05](https://github.com/THOMASELOVE/500-classes-2024/tree/main/class05) | 02-15 | **9 - 11 AM** Propensity Scores: Getting More Comfortable <br /> Discussion of [Lab 2](lab2.qmd) Sketch <br /> Readings: (1) **PRR CI** through Chapter 5, <br /> From [Sources](https://github.com/THOMASELOVE/500-sources): (2) Ahmed et al 2012, <br /> From [Sources](https://github.com/THOMASELOVE/500-sources): (3) Hirano and Imbens 2001
[Project](proj500.qmd) | 02-20 | **Tuesday** 9 AM: [Project](proj500.qmd) Proposal Draft 1 due to [Canvas](https://canvas.case.edu/)
[Class 06](https://github.com/THOMASELOVE/500-classes-2024/tree/main/class06) | 02-22 | **9 - 11 AM** Propensity Scores and Rubin's Rules <br /> Announcement of which OSIA studies will be presented in class <br /> Discussion of Project Proposal Drafts <br /> Readings from [Sources](https://github.com/THOMASELOVE/500-sources): (1) Rubin 2001, <br /> Skim from [Sources](https://github.com/THOMASELOVE/500-sources): (2) Rubin 2004 and (3) Kubo 2020
[Lab 3](lab3.qmd) | 02-29 | [Lab 3](lab3.qmd) due to [Canvas](https://canvas.case.edu/) by the start of class
[Class 07](https://github.com/THOMASELOVE/500-classes-2024/tree/main/class07) | 02-29 | **9 - 11 AM** Propensity Scores and Sensitivity Analyses, [The rhc Example](https://github.com/THOMASELOVE/500-data/tree/master/rhc) <br /> Discussion of [Lab 3](lab3.qmd) Sketch <br /> Readings: **PRR CI** through Chapter 6, <br /> From [Sources](https://github.com/THOMASELOVE/500-sources): (2) Elbadawi 2021 (3) re-skim Connors 1996

## March 2024

LINK | Date | Description
---------: | :-------: | :-----------------------------------------------------
[Project](proj500.qmd) | 03-05 | **Tuesday** 9 AM: [Project](proj500.qmd) Proposal Draft 2 due to [Canvas](https://canvas.case.edu/) <br /> Complete [project scheduling form](https://bit.ly/500-project-schedule-2024).
[Class 08](https://github.com/THOMASELOVE/500-classes-2024/tree/main/class08) | 03-07 | Project and OSIA advice and catch-up <br /> Readings: (1) **PRR CI** through Chapter 7, <br /> From [Sources](https://github.com/THOMASELOVE/500-sources): (2) Tanenbaum 2019
*No Class* | 03-14 | CWRU Spring Break (3-11 through 3-15) <br /> TA office hours also cancelled, and **500-help** will be closed.
[Lab 4](lab4.qmd) | 03-21 | [Lab 4](lab4.qmd) due to [Canvas](https://canvas.case.edu/) by the start of class
[Class 09](https://github.com/THOMASELOVE/500-classes-2024/tree/main/class09) | 03-21 | **9 - 11 AM** [OSIA](osia.qmd) Live Set 1 <br /> Discussion of [Lab 4](lab4.qmd) Sketch <br /> Announcement of Project Presentation Schedule <br /> Reading: **PRR CI** through Chapter 8
[OSIA](osia.qmd) | 03-28 | 9 AM: Recorded [OSIA](osia.qmd) First Reader presentations <br /> due to **Shared Google Drive**
[Class 10](https://github.com/THOMASELOVE/500-classes-2024/tree/main/class10) | 03-28 | **9 - 11 AM** [OSIA](osia.qmd) Live Set 2, More TBA <br /> Reading: **PRR CI** through Chapter 9

## April and May 2024

LINK | Date | Description
---------: | :-------: | :-----------------------------------------------------
-- | 04-01 | Monday TA office hours are cancelled
[Project](proj500.qmd) | 04-02 | **Tuesday** 9 AM: [Project](proj500.qmd) Update due to [Canvas](https://canvas.case.edu/)
-- | 04-03 | Wednesday TA office hours are cancelled
[OSIA](osia.qmd) | 04-04 | 9 AM: Recorded [OSIA](osia.qmd) Second Reader presentations <br /> due to **Shared Google Drive**
[Class 11](https://github.com/THOMASELOVE/500-classes-2024/tree/main/class11) | 04-04 | **9 - 11 AM** [OSIA](osia.qmd) Live Set 3 then Project Update discussion <br /> Reading: **PRR CI** finish book
-- | 04-08 | Monday TA office hours are cancelled in light of the eclipse
[Class 12](https://github.com/THOMASELOVE/500-classes-2024/tree/main/class12) | 04-11 | **8:30 to 11 AM** [Project Presentations](proj500.qmd), Set 1
-- | 04-17 | Wednesday TA office hours are cancelled
[Class 13](https://github.com/THOMASELOVE/500-classes-2024/tree/main/class13) | 04-18 | **8:30 to 11 AM** [Project Presentations](proj500.qmd), Set 2
[Class 14](https://github.com/THOMASELOVE/500-classes-2024/tree/main/class14) | 04-25 | **8:30 to 11 AM** [Project Presentations](proj500.qmd), Set 3
-- | 05-01 | Last Day for TA office hours
[Class 15](https://github.com/THOMASELOVE/500-classes-2024/tree/main/class15) | 05-02 | **8:30 to 11 AM** [Project Presentations](proj500.qmd), Set 4 and Class Wrapup

## End of Semester

- Final Project Submissions are due to [Canvas](https://canvas.case.edu/) at **9 AM on Monday 2023-05-06** from everyone regardless of when you give your project presentation.
- When prompted via email by the University (usually in late April), please visit <https://webapps.case.edu/courseevals/> and complete the course evaluations before they close.


## January 2024

LINK | Date | Description
---------: | :-------: | :-----------------------------------------------------
[Class 01](https://github.com/THOMASELOVE/500-classes-2024/tree/main/class01) | 01-18 | **8:30 to 11 AM** Introduction, Treatments & Randomization <br /> Readings: (1) **PRR CI** through Chapter 2, <br /> From [Sources](https://github.com/THOMASELOVE/500-sources): (2) Benson and Hartz 2000
-- | 01-22 | TA office hours begin and are held most Mondays and Wednesdays 5-6 PM. <br /> Zoom details on our Shared Google Drive and Canvas.
[Lab 0](lab0.qmd) | 01-25 | Get R and RStudio installed/updated on your machine. <br /> Work through [Lab 0](lab0.qmd), referring to the [template and sketch](lab0.qmd). <br /> There's nothing to turn in, but it will help with future labs.
[Class 02](https://github.com/THOMASELOVE/500-classes-2024/tree/main/class02) | 01-25 | **9 - 11 AM** Observational Studies and Propensity Scores <br /> Readings: (1) **PRR CI** through Chapter 3, <br /> From [Sources](https://github.com/THOMASELOVE/500-sources): (2) Abramson Chapter 2 <br /> From [Sources](https://github.com/THOMASELOVE/500-sources): (3) McGowan blog post <br /> From [Sources](https://github.com/THOMASELOVE/500-sources): (4) Bradford Hill 1965