---
title: "Contact Us"
---

If you have a question at any time, send it by email to us at **500-help at case dot edu**.

## Teaching Assistant

Leila Hojat will serve as a teaching assistant for this course, for which I am extremely grateful. Leila has taken the course in the past, and will be happy to help you with questions you have about R, about propensity scores, and about other course materials when I cannot.

Leila’s Office Hours for 500 in Spring 2024 will be held via Zoom from 5 to 6 PM on most Mondays and Wednesdays, beginning Monday 2024-01-22 and continuing through Wednesday 2024-05-01.

- TA office hours are canceled on 2024-03-11 and 2024-03-13 (Spring Break) as well as 2024-04-01 and 2024-04-03, 2024-04-08 (due to the eclipse) and 2024-04-17.
- Zoom meeting details for TA office hours are posted as a Canvas announcement and to our Shared Google Drive. 

## Dr. Love

I will generally be available from 11 to Noon on Thursdays for informal office hours. Just let me know during the break in class if you're planning to chat with me after class.

My additional information is part of the Course Syllabus.